### ISSUE TITLE
Hammersmith Registry>Post TKI therapy>chemo

### ISSUE THREAD

**Issue by afzalkhan500** [fhosking/cml-database#89]
The below "Post-TKI Chemotherapy" is missing. 

![image](https://github.com/user-attachments/assets/8b6d5076-a339-4e3e-ba05-127b1731812d)

**Comment by fhosking** [comment]
I've had to move it to a separate form because it contains too much data to load in addition to the other therapies. However, I can see that the UI needs to improve to help users navigate to the page, so I will sort that out now.

**Comment by fhosking** [comment]
Can I ask about the table, are the left and right panels fully independent of eachother, or does the system automatically link post-tki chemotherapy details episode (right panel) to a specific Post TKI Chemotherapy episode (left panel)?

I can see that records 475, 664, 731, 734 and 864 seem to have multiple chemotherapy episodes
I think that 92 241 273 337 386 401 435 460 475 494 590 664 700 731 734 755 761 864 924 1435 1546 have multiple chemotherapy details

So for 475, 664, 731, 734 and 864, how does the system know which therapy details are tied to which therapy?

![image](https://github.com/user-attachments/assets/18355ae7-3280-4c5a-9d4d-cea64e1f2828)

**Comment by fhosking** [comment]
Great that makes sense. I can replicate that functionality shortly.

**Comment by fhosking** [comment]
Ok, added!

**Comment by afzalkhan500** [comment]
For patient 475 in MS Access it says Yes for "TKI post CT" for both rows but in REDCap it says No:
![image](https://github.com/user-attachments/assets/b434d59b-b1c5-4e6f-b522-e282412f4a5c)
![image](https://github.com/user-attachments/assets/f497395c-ed3d-45cf-b3d6-b70d5aec2d00)

Also for row dated 19/10/2007 the MIDAC is duplicated and the TKI should be Dasatinib Line 3 but it is showing as Nilotinib Line 2:
![image](https://github.com/user-attachments/assets/ca91a133-c03a-4563-ad48-66c15a85a158)
![image](https://github.com/user-attachments/assets/18fb6c2a-9ccc-41fd-bb4b-dd6abcf70009)

**Comment by fhosking** [comment]
I think the MIDAC  duplication was an artefact of us re-importing the data after we've done these fixes. I've reset the form and now I believe this is resolved.

I think there was a similar issue with TKI post CT, i've reworked it and it now seems to correctly show yes/yes for record 475

**Comment by afzalkhan500** [comment]
For patient 475 line dated 19/10/2007 it is still showing Nilotinib Line 2 rather than Dasatinib Line 3:
![image](https://github.com/user-attachments/assets/646f7c44-4bad-4bfd-88de-4a6ab674147d)


Also, "Which Post CT" should be "Which line of TKI post-CT."

**Comment by fhosking** [comment]
<img width="513" alt="image" src="https://github.com/user-attachments/assets/722b5d05-7046-4d29-aa97-c18988df731f">

We can see in the source data table that record 475 ... chemo 2 ... whichtkipostct = 3

So I/we need to determine what lookup table whichtkipostct uses to store tki labels

**Comment by fhosking** [comment]
It must be this one?

<img width="243" alt="image" src="https://github.com/user-attachments/assets/adf9d62c-60b6-46f0-8d12-b12bb8a8f062">

**Comment by afzalkhan500** [comment]
Try that and I will check you're done.

**Comment by fhosking** [comment]
Labels updated

<img width="676" alt="image" src="https://github.com/user-attachments/assets/d51fc096-b020-4350-8ec5-7a574fbd8f24">

**Comment by afzalkhan500** [comment]
That didn't work so please revert back to other list. Could this again be due to different versions of MS Access databases? I will email you the most recent database the we can check again.

**Comment by afzalkhan500** [comment]
It's messed up the 15/12/2006 which should be Nilotinib Line 2 and Dasatinib Line 3 but is showing as Dasatinib Line 2 and Imatinib Line 3. for 19/10/2007 Dasatinib is correct but the Line should be 3 not 2.

**Comment by fhosking** [comment]
I have imported the new dataset. unfortunately 475 therapy 1 detail 2 now shows Nilotinib 

![image](https://github.com/user-attachments/assets/c9f33f9e-276f-425a-8c13-92329043b8e9)

**Comment by fhosking** [comment]
I've also reverted the labelling scheme to the previous one as requested

**Comment by fhosking** [comment]
Perhaps the issue is that whichtkipostct and whichpostct are the wrong way around?

**Comment by afzalkhan500** [comment]
Yes, you are right! I exported the data for patient 386 and it shows:
![image](https://github.com/user-attachments/assets/dedb4914-b382-4087-9447-d5e49af99dff)

So "Which line of TKis post-CT" is the TKI name and "Which line of TKIs post-DLI" is the line
Try switching and I will check.

**Comment by fhosking** [comment]
Updated. 475 now gives Dasatinib

<img width="580" alt="image" src="https://github.com/user-attachments/assets/b8ccfdb9-8f68-4a7a-a865-d208befd4627">

**Comment by afzalkhan500** [comment]
Yes! That works for both patients 475 and 386!
